<a href="https://colab.research.google.com/github/crinex/what-is-numpy/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Numpy
- Numpy는 수학, 과학 연산을 위한 파이썬 패키지이다.
- Numerical + Python의 합성어이다.

### 기본 사용 방법
- Numpy는 보통 숫자로 구성되는 Array는 모두 동일한 타입의 요소를 갖는다.
- 음이 아닌 정수로 인덱싱된다.

In [1]:
import numpy as np

x = np.array([1, 2, 3])
x

array([1, 2, 3])

In [2]:
# Numpy는 다양한 함수로 다양한 형태의 행렬을 만들 수 있다.
a = np.zeros(3)
b = np.ones((2, 3))

print(a)
print(b)

[0. 0. 0.]
[[1. 1. 1.]
 [1. 1. 1.]]


### 수학 연산

In [5]:
x = np.array([1.,2.,3.,4.])
y = np.array([5.,6.,7.,8.])

# 두 Array의 합
print(np.add(x, y))
# 두 Array의 곱
print(np.multiply(x, y))
# Array의 평균
print(np.mean(x))

[ 6.  8. 10. 12.]
[ 5. 12. 21. 32.]
2.5


### 난수 생성
- rand 함수는 0~1까지의 범위에서 균일한 분포를 갖는 숫자 샘플링
- randn 함수는 표준정규분포를 갖는 숫자 샘플링

In [6]:
x = np.random.rand(2, 5)
y = np.random.randn(3, 4)

print(x)
print(y)

[[0.58497301 0.02671962 0.00287282 0.10646867 0.53911534]
 [0.87749374 0.12087335 0.85068104 0.56790274 0.13057793]]
[[-1.2608639   0.77337739  1.89984148  2.49092282]
 [-1.23096063 -0.77149982  1.03182675  0.58373308]
 [ 1.35110238 -0.54122385  0.84248547  1.36324682]]


## Array 생성하기
- np.array()함수에 파이썬 리스트, 튜플을 입력하면 Numpy의 Array가 만들어진다.

In [7]:
a = np.array([1, 2, 3])

print(a)         # a안에 들어있는 데이터
print(a.shape)   # a의 크기
print(type(a))   # a의 자료형
print(a.dtype)   # a 요소의 데이터 타입(자료형)

[1 2 3]
(3,)
<class 'numpy.ndarray'>
int64


## Arange 생성하기
- np.arange는 연속적인 숫자를 만들기 위한 함수로 파이썬의 range()와 비슷한 함수다.
- 리스트대신 어레이를 반환값으로 준다.

In [8]:
# 0부터 5까지 step=1을 기준으로 어레이 생성
x = np.arange(0, 5, 1)
x

array([0, 1, 2, 3, 4])